// <auto-generated />
using ConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190728082802_T1")]
    partial class T1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ConsoleApp.Rabbit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Rabbits");
                });

            modelBuilder.Entity("ConsoleApp.Sheep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rabbit1Id");

                    b.Property<int>("Rabbit2Id");

                    b.HasKey("Id");

                    b.HasIndex("Rabbit1Id");

                    b.HasIndex("Rabbit2Id");

                    b.ToTable("Sheeps");
                });

            modelBuilder.Entity("ConsoleApp.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("ConsoleApp.Manager", b =>
                {
                    b.HasBaseType("ConsoleApp.User");

                    b.Property<string>("LastName");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("ConsoleApp.Publisher", b =>
                {
                    b.HasBaseType("ConsoleApp.User");

                    b.Property<int>("Credit");

                    b.HasDiscriminator().HasValue("Publisher");
                });

            modelBuilder.Entity("ConsoleApp.Post", b =>
                {
                    b.HasOne("ConsoleApp.User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ConsoleApp.Sheep", b =>
                {
                    b.HasOne("ConsoleApp.Rabbit", "Rabbit1")
                        .WithMany("Sheeps1")
                        .HasForeignKey("Rabbit1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConsoleApp.Rabbit", "Rabbit2")
                        .WithMany("Sheeps2")
                        .HasForeignKey("Rabbit2Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
